name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for creating an issue - we really appriciate your feedback - please give us a moment to get to it'' first issue'
        pr-message: 'Thank you for your contribution - we really appriciate your improvement - please give us a moment to get to it'' first pr'
